import type { GqlRemarkFileInfo } from '@/__generated__/graphql';

//////////////////////////
// COLLECTION
//////////////////////////

/**
 * Interface of an entry as it is present in the gridsome / lokiJS collection.
 * 
 * Note that this is different from the input that's parsed from the frontmatter,
 * as well as different from the GraphQL type that's exposed:
 * 
 * Input --[enrich and insert into db]--> CollectionNode --[expose]--> GqlNode
 */
export interface CollectionNode<TType extends string = string> {
  id: string;
  $uid: string;
  path: string;
  excerpt: string | null;
  content: string | null;
  /** Generated by markdown source parser */
  fileInfo: Omit<GqlRemarkFileInfo, '__typename'>;
  internal: {
    typeName: TType;
    origin: string;
    mimeType: null | string;
    content: null | string;
    timestamp: number;
  };
};
